package exception_handing;

public class finall {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try
		{
			System.out.println("try");
		}
		catch (ArithmeticException w)
		{
			System.out.println("catch");
		}
finally
{
	System.out.println("finally");
}
	}

}
